@baseUrl = http://localhost:8000
@device = test_device

### Health
GET {{baseUrl}}/health

### List devices
GET {{baseUrl}}/devices

### Latest for all devices
GET {{baseUrl}}/devices/latest

### Latest for one device
GET {{baseUrl}}/devices/{{device}}/latest

